Update deploy.yml
ajuste caminho diretorio lambda_function .py e .zip

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,13 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
+    - name: List files in the lambda_function directory
+      run: ls -la lambda_function
+
+    - name: Check if lambda_function.py exists in lambda_function directory
+      run: |
+        if [ ! -f lambda_function/lambda_function.py ]; then echo "File not found!"; exit 1; fi
+
     - name: Package Lambda Function
       run: zip -r lambda_function.zip lambda_function/lambda_function.py
 
